### ISSUE TITLE
Issues after upgrading to 2.5.1

### ISSUE THREAD

**Issue by zitstif** [as247/wordpress-2-step-verification#4]
Thank you for your hard work and contributions. I'm currently having an issue with WP2sv 2.5.1. It constantly says this message: 
"Wp2sv database update required
Wp2sv has been updated! To keep things running smoothly, we have to update your database to the newest version. The database update process runs in the background and may take a little while, so please be patient."

I have given it many hours to complete and it still stands. I've restarted the apache daemon and rebooted the system as well but this issue persists. 

The system is a pretty common LAMP stack and it's nothing too special. Any idea how can I resolve this?

**Comment by zitstif** [comment]
If I comment out this section, the message goes away:

    function runBackgroundUpgrade(){
        if($this->needUpdate()) {
                        if (!wp_next_scheduled('wp2sv_upgrade')) {
                                wp_schedule_single_event(time(), 'wp2sv_upgrade');
                        }
                        #add_action('admin_notices',[$this,'noticeUpgrade']);
                }
        }


wordpress-2-step-verification/includes/Wp2sv_Upgrade.php

**Comment by as247** [comment]
This task will run in background, then if you running at local or somewhere that wp cron not work, then it not able to update database.
You may:
1. Run upgrade task manually by run [wp-cli](https://wp-cli.org/) command: wp cron event run wp2sv_upgrade
2. Configure wp cron to run by system https://developer.wordpress.org/plugins/cron/hooking-wp-cron-into-the-system-task-scheduler/

**Comment by zitstif** [comment]
Is this the first time w2sv has done a database upgrade? I've upgraded the program before and it's never given me these issues. I've used it with wp-cron enabled and disabled without issues.

**Comment by as247** [comment]
I move upgrade task to background and add notification since 2.5, before 2.5 upgrade run synchronously when any admin page loaded
